#ifndef PARAMS_DEFINED
#define PARAMS_DEFINED

#define PE_ROWS 8
#define PE_COLS 8

#define KERNEL_CACHE_LANES PE_ROWS
#define KERNEL_CACHE_LANE_MASK 0x7
#define KERNEL_CACHE_DEPTH 4096
#define KERNEL_CACHE_DEPTH_MASK 0xFFF

#define KERNEL_INDEX_CACHE_DEPTH 512
#define KERNEL_INDEX_CACHE_DEPTH_MASK 0x1FF
#define KERNEL_INDEX_CACHE_LANES KERNEL_CACHE_LANES

#endif

