#ifndef PARAMS_DEFINED
#define PARAMS_DEFINED

#define INSTRUCTION_SIZE 27
#define COMMAND_SIZE_BYTES 26
#define MAX_INSTRUCTION_TYPE_BITS 16
#define INSTRUCTION_HEADER_OFFSET 26
#define INSTRUCTION_HEADER_BYTES 1
#define INSTRUCTION_COMMAND_BYTES 24 
#define INSTRUCTION_DEPENDENCY_HIGH_OFFSET 1
#define INSTRUCTION_DEPENDENCY_LOW_OFFSET 0

#ifdef WEIGHT_MEMORY_TEST
//Instruction IDs
#define OPCODE_FILL_WEIGHT_BUFFER 0x1
#define OPCODE_DRAIN_WEIGHT_BUFFER 0X2
#define OPCODE_SWAP_WEIGHT_BUFFER 0x3
#define OPCODE_COLLECT_WEIGHT 0X4

#define NUM_TRANSPORTS 0x4

#define TRANSPORT_ID_FILL_WEIGHT_BUFFER 0X0
#define TRANSPORT_ID_DRAIN_WEIGHT_BUFFER 0X1
#define TRANSPORT_ID_SWAP_WEIGHT_BUFFER 0x2
#define TRANSPORT_ID_COLLECT_WEIGHT 0X3

//Transport IDs
#define WEIGHT_DMA_INSTRUCTION_TRANSPORT_ID 0x0
#define WEIGHT_BUFFER_INSTRUCTION_TRANSPORT_ID 0X1
#define WEIGHT_COLLECTOR_INSTRUCTION_TRANSPORT 0x2
#endif

//=======Number of bits allocated to the zero count and the weight
#define WEIGHT_ZCOUNT_BITWIDTH 4
#define WEIGHT_ZCOUNT_BITOFFSET 12
#define WEIGHT_ZCOUNT_MASK 0xF000
#define WEIGHT_BITWIDTH 12
#define WEIGHT_BITOFFSET 0
#define WEIGHT_MASK 0x0FFF
//================================================================


#define PACKET_SIZE 1

#define PE_ROWS 8
#define PE_COLS 8

#define KERNEL_CACHE_LANES PE_ROWS
#define KERNEL_CACHE_LANE_MASK 0x7
#define KERNEL_CACHE_DEPTH 8192
#define KERNEL_CACHE_DEPTH_MASK 0x1FFF

#define KERNEL_INDEX_CACHE_DEPTH 512
#define KERNEL_INDEX_CACHE_DEPTH_MASK 0x1FF
#define KERNEL_INDEX_CACHE_LANES KERNEL_CACHE_LANES

#endif

