// a10_mac_8bitx2.v

// Generated using ACDS version 17.1.1 273

`timescale 1 ps / 1 ps
module a10_mac_8bitx2 (
		input  wire        clock0,  //  clock0.clock0
		input  wire [7:0]  dataa_0, // dataa_0.dataa_0
		input  wire [7:0]  dataa_1, // dataa_1.dataa_1
		input  wire [7:0]  datab_0, // datab_0.datab_0
		input  wire [7:0]  datab_1, // datab_1.datab_1
		output wire [31:0] result   //  result.result
	);

	a10_mac_8bitx2_altera_mult_add_171_72klhga mult_add_0 (
		.result  (result),  //  output,  width = 32,  result.result
		.dataa_0 (dataa_0), //   input,   width = 8, dataa_0.dataa_0
		.dataa_1 (dataa_1), //   input,   width = 8, dataa_1.dataa_1
		.datab_0 (datab_0), //   input,   width = 8, datab_0.datab_0
		.datab_1 (datab_1), //   input,   width = 8, datab_1.datab_1
		.clock0  (clock0)   //   input,   width = 1,  clock0.clock0
	);

endmodule
